### ISSUE TITLE
[Feature] 테스트 코드 도입

### ISSUE THREAD

**Issue by BoubleJ** [Keyword-Project/keyword_searcher_project_frontend#15]
### Jest 라이브러리를 활용한 테스트 코드 구현을 통해 TDD 시도 

- 프론트엔드도 테스크코드 구현해야한다길래 시도해봄
- 원래 프로젝트 시작하면서 만들어야한다는데 그래도 일단 해봄
- 공식문서를 보면서 천천히 시도해볼 것

## ESTIMATE
1.5 Day

## TASKS

- [ ] Jest를 이용한 테스트 코드 구현
- [ ] commit 혹은 pr 시 테스트 자동화 구현
   - [ ] 디스코드나 노션에 알람이 가면 더할나위없이 좋다.
