### ISSUE TITLE
[Refactor] Redux Toolkit + React-Query 적용

### ISSUE THREAD

**Issue by BoubleJ** [Keyword-Project/keyword_searcher_project_frontend#4]
## ISSUE

- 서버상태 관리, 캐싱기능, 데이터 갱신 옵션 설정이 가능한 리액트 쿼리가 본 프로젝트에 적합하다 판단되어 마이그레이션 시도
- 하지만 리액트 쿼리는 전역관리 라이브러리 라기보단 서버상태관리 라이브러리에 가깝기 때문에 redux와 병행해서 사용할지 보류
-  조사 결과 Client 데이터는 상태 관리 라이브러리가 관리, Server 데이터는 React-Query가 관리하는 구조가 가장 이상적인 형태라고 한다. redux toolkit과 react-query 병행 사용 채택

참고링크 : [React-Query](https://velog.io/@kandy1002/React-Query-%ED%91%B9-%EC%B0%8D%EC%96%B4%EB%A8%B9%EA%B8%B0)

## ESTIMATE

1 Day

## TASKS

- [x]  React-Query -> 서버 데이터 관리
   - [x]  API 호출 데이터 캐싱 기능 구현
   - [ ] 무한 스크롤 구현
- [x]  Redux-Toolkit  -> 클라이언트 데이터 관리
