### ISSUE TITLE
[Design] Figma 디자인 시스템 및 도안 기반 UI 수정

### ISSUE THREAD

**Issue by BoubleJ** [Keyword-Project/keyword_searcher_project_frontend#6]
### Figma 디자인 시스템 및 도안 기반 UI 수정

- 모아나가 만들어준 디자인 시스템 및 페이지 도안 기반 UI 수정하기
- 스타일 속성 전역 변수 활용
- 피그마가 지원하는 jsx 코드는 온갖 스타일 속성이 도배 되어있기 때문에 css 속성 참고 지양. 

![Image](https://github.com/Keyword-project/Keyword_Searcher_Project_frontend/assets/122145341/0bfb923c-e5f5-4a0c-bd66-6831fca256bc)

## ESTIMATE
3Day

## TASKS

해야할 일 세부 리스트 작성

- [x] 공용 컴포넌트(Button, Input, Dropdown 등) 제작
- [x] Header 제작
- [x] 글꼴 적용
- [x] 카테고리 list container 제작
- [x] 데이터 출력 테이블 제작
